language: python
python:
  - "2.7"
  - "3.6"
# command to install Ubuntu packages before installing
before_install:
  - sudo apt-get update -qq
# command to install dependencies
install: "pip install pycroscopy"
# command to run tests
script: pytest